# Generated by Django 5.0.1 on 2024-01-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emp',
            new_name='products',
        ),
    ]
