# Generated by Django 5.0.1 on 2024-01-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchapp', '0002_rename_emp_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='disprice',
        ),
    ]
