# Generated by Django 5.0.1 on 2024-01-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchapp', '0007_alter_products_disprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='disprice',
        ),
    ]
