# Generated by Django 5.0.1 on 2024-01-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchapp', '0011_userextrainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='footwear', max_length=40),
        ),
    ]
