# Generated by Django 5.0.1 on 2024-01-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchapp', '0012_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default='ab', max_length=200),
        ),
    ]
