# Generated by Django 5.0.1 on 2024-01-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchapp', '0013_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(max_length=40),
        ),
    ]
