# Generated by Django 5.0.1 on 2024-01-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchapp', '0014_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='totalsells',
            field=models.IntegerField(default=1),
        ),
    ]
