# Generated by Django 5.0.1 on 2024-02-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchapp', '0018_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextrainfo',
            name='profilepic',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
